//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqProject2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqProject2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,11,1
        ///1,5,9,2
        ///1,7,5,1
        ///2,2,32,1
        ///2,4,2,1
        ///3,3,43,1
        ///3,8,1,3
        ///3,7,15,1
        ///3,2,22,1
        ///4,4,4,1
        ///4,5,2,1
        ///5,5,1,1
        ///5,6,1,10
        ///6,6,1,1
        ///6,1,2,2
        ///6,3,3,1
        ///6,8,5,1
        ///6,7,7,1
        ///6,2,11,1
        ///7,7,8,1
        ///8,8,9,1
        ///.
        /// </summary>
        internal static string Ownership {
            get {
                return ResourceManager.GetString("Ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bradley,1,pacprof,Chicago,TRUE
        ///Clayton,2,pokechamp,Chicago,FALSE
        ///Tina,3,pikachu,Chicago,TRUE
        ///James,4,ilikethis,Kansas City,TRUE
        ///Timothy,5,noname,Tampa Bay,FALSE
        ///Gerald,6,someguy,Las Vegas,TRUE
        ///Alex,7,nomoreideas,Seatlle,TRUE
        ///Bill,8,seriouslynone,Kansas City,FALSE
        ///Evan,9,ihatepokemon,Wheaton,FALSE
        ///.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Pokedata&gt;
        ///&lt;Players&gt;
        ///&lt;player&gt;&lt;name&gt;Bradley&lt;/name&gt;&lt;number&gt;1&lt;/number&gt;&lt;nickname&gt;pacprof&lt;/nickname&gt;&lt;city&gt;Chicago&lt;/city&gt;&lt;paid&gt;TRUE&lt;/paid&gt;&lt;/player&gt;
        ///&lt;player&gt;&lt;name&gt;Clayton&lt;/name&gt;&lt;number&gt;2&lt;/number&gt;&lt;nickname&gt;pokechamp&lt;/nickname&gt;&lt;city&gt;Chicago&lt;/city&gt;&lt;paid&gt;FALSE&lt;/paid&gt;&lt;/player&gt;
        ///&lt;player&gt;&lt;name&gt;Tina&lt;/name&gt;&lt;number&gt;3&lt;/number&gt;&lt;nickname&gt;pikachu&lt;/nickname&gt;&lt;city&gt;Chicago&lt;/city&gt;&lt;paid&gt;TRUE&lt;/paid&gt;&lt;/player&gt;
        ///&lt;player&gt;&lt;name&gt;James&lt;/name&gt;&lt;number&gt;4&lt;/number&gt;&lt;nickname&gt;ilikethis&lt;/nickname&gt;&lt;city&gt;Kansas City&lt;/city&gt;&lt;paid&gt;TRUE&lt;/paid&gt;&lt;/player [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pokedata {
            get {
                return ResourceManager.GetString("pokedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Bulbasaur,120,130
        ///2,Squirtle,130,120
        ///3,Rattata,110,140
        ///4,Pickachu,100,150
        ///5,Jigglypuff,90,160
        ///6,Jynx,50,200
        ///7,Ditto,220,30
        ///8,Seaking,150,100
        ///.
        /// </summary>
        internal static string Pokemon {
            get {
                return ResourceManager.GetString("Pokemon", resourceCulture);
            }
        }
    }
}
